apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  namespace: backendca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
      - name: authservice
        image: "mytestca.azurecr.io/nginx:#{Build.BuildID}#"
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: authservice
  namespace: backendca
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  selector:
    app: authservice